/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import FightScene from "./script/scene/fightScene/FightScene"
import InitScene from "./script/scene/initScene/InitScene"
import LoginScene from "./script/scene/loginScene/LoginScene"
import MainScene from "./script/scene/mainScene/MainScene"
import TransitionScene from "./script/scene/transitionScene/TransitionScene"
import AlertComp from "./script/commonUI/AlertComp"
import FpsComp from "./script/commonUI/FpsComp"
import ToastComp from "./script/commonUI/ToastComp"
import FightPreloadUI from "./script/scene/fightScene/fightUI/FightPreloadUI"
import FightUI from "./script/scene/fightScene/FightUI"
import InitUI from "./script/scene/initScene/InitUI"
import LoginUI from "./script/scene/loginScene/LoginUI"
import SelectServer from "./script/scene/loginScene/SelectServer"
import SelectServerItem from "./script/scene/loginScene/SelectServerItem"
import MainUI from "./script/scene/mainScene/MainUI"
import TransitionUI from "./script/scene/transitionScene/TransitionUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="init/InitScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/scene/fightScene/FightScene.ts",FightScene);
        reg("script/scene/initScene/InitScene.ts",InitScene);
        reg("script/scene/loginScene/LoginScene.ts",LoginScene);
        reg("script/scene/mainScene/MainScene.ts",MainScene);
        reg("script/scene/transitionScene/TransitionScene.ts",TransitionScene);
        reg("script/commonUI/AlertComp.ts",AlertComp);
        reg("script/commonUI/FpsComp.ts",FpsComp);
        reg("script/commonUI/ToastComp.ts",ToastComp);
        reg("script/scene/fightScene/fightUI/FightPreloadUI.ts",FightPreloadUI);
        reg("script/scene/fightScene/FightUI.ts",FightUI);
        reg("script/scene/initScene/InitUI.ts",InitUI);
        reg("script/scene/loginScene/LoginUI.ts",LoginUI);
        reg("script/scene/loginScene/SelectServer.ts",SelectServer);
        reg("script/scene/loginScene/SelectServerItem.ts",SelectServerItem);
        reg("script/scene/mainScene/MainUI.ts",MainUI);
        reg("script/scene/transitionScene/TransitionUI.ts",TransitionUI);
    }
}
GameConfig.init();